import angular from 'angular';

import AppController from './config/app.controller'
import appRun from './config/app.run';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './service';


// Create and bootstrap application
const requires = [
    'templates',
    'app.services',
];

// Mount on window for testing
window.app = angular.module('app', requires);
angular.module('app').controller('AppController', AppController);
angular.module('app').run(appRun);
angular.bootstrap(document, ['app'], {
    strictDi: true
});
